### ISSUE TITLE
rendering instructions

### ISSUE THREAD

**Issue by mzhaoshuai** [xplip/pixel#5]
Thanks for your wonderful work!
I am very interested in your work and try to extend the ideas to other tasks.
I wonder when the rendering instructions will be available?

**Comment by mzhaoshuai** [comment]
I figure out how to render text. following https://github.com/xplip/pixel/blob/main/scripts/data/prerendering/prerender_bookcorpus.py.

Another question is how can I get emojis as shown in Figure 2 in the paper?
Are these emojis added in some automatic manner, or, emojis are part of the corpus and you do not manipulate them?
<img width="948" alt="image" src="https://user-images.githubusercontent.com/22476764/194743539-4da93dd1-5d0e-4c28-be00-d7e12c41b93c.png">


Personally, I am also interested in the performance of the language model without such emojis which contain image concepts. Will these emojis help language modeling?

**Comment by xplip** [comment]
Thanks for your interest in PIXEL! I can try to write up a small rendering guide this week to help use and extend our renderer.

The prerendering script you found is using the `PyGameTextRenderer` but I would generally recommend that you use the `PangoCairoTextRenderer` which has broader language support and support for the emojis you mentioned.

After setting up your environment as described [here](https://github.com/xplip/pixel#setup), you can render an image similar to the one in the paper like this:

```python
from pixel import PangoCairoTextRenderer
from PIL import Image

# Load renderer with fallback fonts and RGB rendering enabled
text_renderer = PangoCairoTextRenderer.from_pretrained(
    "Team-PIXEL/pixel-base",
    fallback_fonts_dir="path/to/your/fallback_fonts",
    rgb=True
)

sentence = "My cat 🐈 loves pancakes 🥞 and my duck 🦆 loves grapes 🍇."

# Render the sentence; returns an Encoding object
encoding = text_renderer(sentence)

# Create image from pixel values; img will have dimensions 3x16x8464 by default
img = Image.fromarray(encoding.pixel_values)

# Save to disk to visualize
img.save("test.png")
```

Note that you’re going to need an emoji font like `AppleColorEmoji.ttf` to successfully render emojis and you need to instantiate a renderer with the `rgb=True` argument to render it in color.

See [here](https://github.com/xplip/pixel/blob/main/.github/FINETUNING.md#downloading-data-and-fallback-fonts) for instructions on how to download our fallback fonts.

We haven’t done much experimentation with emojis yet. They may or may not help in language modelling, but personally I think they will primarily help for tasks that explicitly make use of emoji such as sentiment analysis of social media texts.

If you aren’t interested in emoji, then I recommend you do not use the `rgb=True` argument because RGB rendering is slightly slower than grayscale rendering. However, I strongly recommend to use fallback fonts regardless.

I hope this helped for now and as I mentioned I will try to write up something more detailed later this week. Let me know if you have further questions :).

**Comment by mzhaoshuai** [comment]
Thanks for your detailed response!
